# Generated by Django 5.2.17 on 2026-10-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0006_occurrence_defesa_civil_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='source_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
