# Generated by Django 5.2.17 on 2026-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0027_normalize_territory_names'),
        ('occurrences', '0007_alter_occurrence_source_alter_occurrence_source_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='occurrence',
            name='unique_occurrence_source_row_neighborhood',
        ),
        migrations.RemoveIndex(
            model_name='occurrence',
            name='occ_neigh_datetime_idx',
        ),
        migrations.RemoveIndex(
            model_name='occurrence',
            name='occ_datetime_idx',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='displaced',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='injured',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='missing',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='people_affected',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='sheltered',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='sick',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='source',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='source_ref',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='source_row',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='time_precision',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='wind_speed_kmh',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='situation',
            field=models.IntegerField(choices=[(1, 'Alerta'), (2, 'Atenção'), (3, 'Emergência'), (4, 'Normalidade')], default=4),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alagamento'), (2, 'Chuvas Intensas'), (3, 'Enxurrada'), (4, 'Inundação')], default=1),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='neighborhood',
            field=models.ManyToManyField(related_name='occurrences', to='addressing.neighborhood'),
        ),
    ]
