# Generated by Django 5.2.17 on 2026-09-11 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_camera_monitoring', '0019_operational_alerts'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMonitoringState',
            fields=[
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='monitoring', serialize=False, to='flood_camera_monitoring.camera')),
                ('level', models.CharField(default='NORMAL', max_length=12)),
                ('reason', models.CharField(default='INITIAL', max_length=200)),
                ('next_analysis_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('strong_streak', models.PositiveIntegerField(default=0)),
                ('clear_streak', models.PositiveIntegerField(default=0)),
                ('last_probability', models.FloatField(null=True)),
                ('manual_until', models.DateTimeField(null=True)),
                ('context_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(max_length=12)),
                ('result', models.JSONField(default=dict)),
                ('frames', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='flood_camera_monitoring.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('size', models.PositiveIntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='flood_camera_monitoring.cameraanalysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='CameraReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='flood_camera_monitoring.cameraanalysisrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flood_camera_monitoring.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloodModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(default='torch', max_length=32)),
                ('artifact_path', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('manifest', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('status', models.CharField(default='candidate', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'champion')), fields=('status',), name='one_flood_champion')],
            },
        ),
    ]
