# Generated by Django 5.2.17 on 2026-09-11 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_camera_monitoring', '0020_adaptive_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerareview',
            name='approval_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flood_camera_monitoring.camerareview'),
        ),
        migrations.AddField(
            model_name='camerareview',
            name='event_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ModelShadowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilities', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flood_camera_monitoring.floodmodelversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shadow_results', to='flood_camera_monitoring.cameraanalysisrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'model'), name='unique_shadow_run_model')],
            },
        ),
    ]
