# Generated by Django 5.2.17 on 2026-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('flood', models.FloatField()),
                ('probability', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
                'unique_together': {('latitude', 'longitude', 'datetime')},
            },
        ),
    ]
