# Generated by Django 5.2.17 on 2026-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_occurrence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weather',
            name='unique_weather_per_day_location',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='occurrence',
        ),
        migrations.AddField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='neighborhood',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='river_discharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
