# Generated by Django 5.2.17 on 2026-09-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weather_unique_weather_per_day_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
