# Generated by Django 5.2.17 on 2026-10-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weather_unique_weather_per_day_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='datetime',
        ),
    ]
